### ISSUE TITLE
Error swallowing

### ISSUE THREAD

**Issue by stylesuxx** [chill117/data-sourcer#14]
Every `catch(done)`
https://github.com/chill117/data-sourcer/blob/3f6a65e2e07b442cff448316516a8f2ef958497b/index.js#L593

shout actually emit an error, also I think it should emit an **end** state.

This issue is related:
* https://github.com/chill117/proxy-lists/issues/90

I found that all proxy sources that use puppeteer don't work for me and are caught by that catch (and basically dismissed).

The error that was responsible for my problems is:

```
Error Error: Failed to launch chrome!
[28535:28535:0713/200757.545458:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
```

I can now do something about my problems.

@chill117 you mentioned that you are refactoring this in regards to the errors - let me know if I can help you out in any way. I think for you it should be a quick thing to solve those problems, but if you don't have time, I'll dig into the codebase and submit a PR.

**Comment by chill117** [comment]
Good find. This looks like the source of your troubles at the moment. Specifically this line:
https://github.com/chill117/data-sourcer/blob/3f6a65e2e07b442cff448316516a8f2ef958497b/index.js#L565

Failing early, and loudly, is preferable in my mind so let's throw an error inside `prepareBrowser` in the case that no callback (`done`) is passed by the user. Then we just fix the usage by `preparePage` referenced above. This will allow users to catch the problems with puppeteer much sooner.

**Comment by chill117** [comment]
Fixed by https://github.com/chill117/data-sourcer/commit/1e0ddd937955a0066371096c4003430f218dff7e
