### ISSUE TITLE
List crawler broken

### ISSUE THREAD

**Issue by stylesuxx** [chill117/data-sourcer#15]
I have problems with the list-crawler.

Using it with the proxy-lists module. The *data* signal is not emitted, at least when using the blackhatworld source. Also the browser window stays open, although the end signal is emitted (for debug purposes I set the headless option to false).

**Comment by chill117** [comment]
Is this related to #14 perhaps? Or does this still happen even after you've fixed your problem with puppeteer?

**Comment by stylesuxx** [comment]
No, this does still happen after fixing the problem with puppeteer. I run puppeteer in "headfull" mode and can see that it is opening the pages and also parsing the info, but the data signal is simply not emitted... Did some printf debugging. Interestingly end is emitted, but puppeteer or the chromium windom for that matter is still open.

**Comment by stylesuxx** [comment]
Your latest commit, that fixed #14 - also fixed this one for me. I am closing it.
Thank you very much.
