### ISSUE TITLE
hidemyna.me source stuck on 403 HTTP error

### ISSUE THREAD

**Issue by stylesuxx** [chill117/data-sourcer#18]
With the hidemyna.me proxy source, the page will throw a 403 error, in this case the tab is never closed - it seems there is also no time out triggered - the tab stays open indefinitely and blocks further execution.

I would expect the selector timeout to be triggered at some point, but it does not.

**Comment by chill117** [comment]
This looks like a special case with the hidemyna.me source which is protected by CloudFlare's anti-DDOS service. The HTTP 403 error might be happening when the user of the browser is required by CloudFlare to complete a CAPTCHA and then fails. In this case perhaps we can have the source gracefully fail (emit an error about what happened and then emit the end event).

**Comment by stylesuxx** [comment]
OK, sounds good to me.

**Comment by chill117** [comment]
Fixed and will be released in the next version.
