### ISSUE TITLE
Browser not closed

### ISSUE THREAD

**Issue by stylesuxx** [chill117/data-sourcer#19]
As mentioned in #16 the tabs are being closed once the sourcer is done, still the browser is kept open. Tried with `proxy-lists` and `data-sourcer` latest master branch.

**Comment by chill117** [comment]
Each instance of data-sourcer uses a single instance of puppeteer's browser object. Multiple calls to `getData` or `getDataFromSource` will all use the same browser instance - they will spawn their own page (tab) instances to load web pages and scrape data.

If you're expecting the browser will be closed completely after each call to `getData` or `getDataFromSource` then each of these method calls will have to spawn their own browser instance - which would use more memory. Alternatively, it could be possible to implement some kind of async.queue that once drained (empty, all tasks done) it would cause the current browser instance to be closed and then the next calls to `getData` or `getDataFromSource` would create a new browser instance.

**Comment by stylesuxx** [comment]
OK, but then proxy-lists should call the close function once it has finished retrieving all the proxies. Maybe the issue should be moved to the `proxy-lists` repo then...

**Comment by chill117** [comment]
Changes in the downstream module ([ProxyLists](https://github.com/chill117/proxy-lists)):
> Calls to `getProxies` and `getProxiesFromSource` will now both clean-up by calling the `dataSourcer.close` method once all the sources have sent their end event. This has the effect of automatically closing any browser instances used by proxy sources.

**Comment by chill117** [comment]
Marking this closed as it was solved downstream.
